#!/bin/bash

if [[ -n $1 ]] 
    then
    
    rm -f -r ../GOOLINPUTCPP/*
    rm -f ../GOOLOUTPUTJAVA/src/*
    cp t$1/* ../GOOLINPUTCPP/
    echo "####### t$1 chargé #######"
    cat t$1/*
    
    echo ""
    echo "####### Press any key to run CppRecognizer ... #######"
    read
    ./script_run_reco

else

nbt=5

for ((i=1 ; $i <= $nbt ; i++)) do
    rm -f -r ../GOOLINPUTCPP/*
    rm -f ../GOOLOUTPUTJAVA/src/*
    cp t${i}/* ../GOOLINPUTCPP/
    echo "t${i} chargé :"
    cat t${i}/*
    read
done

    rm -f -r ../GOOLINPUTCPP/*
    rm -f ../GOOLOUTPUTJAVA/src/*
    cp tall/* ../GOOLINPUTCPP/
    echo "tall chargé :"
    cat tall/*
    read

    rm -f -r ../GOOLINPUTCPP/*
    rm -f ../GOOLOUTPUTJAVA/src/*
    cp terreur/* ../GOOLINPUTCPP/
    echo "terreur chargé :"
    cat terreur/*

    rm -f -r ../GOOLINPUTCPP/*
    rm -f ../GOOLOUTPUTJAVA/src/*
    cp tprepro/* ../GOOLINPUTCPP/
    echo "tprepro chargé :"
    cat tprepro/*
    read

    rm -f -r ../GOOLINPUTCPP/*
    rm -f ../GOOLOUTPUTJAVA/src/*
    cp tlib/* ../GOOLINPUTCPP/
    echo "tlib chargé :"
    cat tlib/*

fi
