/* Generated By:JJTree: Do not edit this line. CPPAST_CTOR_DEFINITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_CTOR_DEFINITION extends SimpleNode {
  public CPPAST_CTOR_DEFINITION(int id) {
    super(id);
  }

  public CPPAST_CTOR_DEFINITION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3fdad00c5350b9f036693d47920256ee (do not edit this line) */
