/* Generated By:JJTree: Do not edit this line. CPPAST_MEMBER_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_MEMBER_DECLARATOR extends SimpleNode {
  public CPPAST_MEMBER_DECLARATOR(int id) {
    super(id);
  }

  public CPPAST_MEMBER_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c037d6c40296a55f656a7f4c4f058b0c (do not edit this line) */
