/* Generated By:JJTree: Do not edit this line. CPPAST_CLASS_HEAD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_CLASS_HEAD extends SimpleNode {
  public CPPAST_CLASS_HEAD(int id) {
    super(id);
  }

  public CPPAST_CLASS_HEAD(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=32095d6e9184f550d4841782f8639c23 (do not edit this line) */
