/* Generated By:JJTree: Do not edit this line. CPPAST_EXCEPTION_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_EXCEPTION_DECLARATION extends SimpleNode {
  public CPPAST_EXCEPTION_DECLARATION(int id) {
    super(id);
  }

  public CPPAST_EXCEPTION_DECLARATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c38bbed92b3d87522837b09ac5291edf (do not edit this line) */
