/* Generated By:JJTree: Do not edit this line. CPPAST_TRANSLATION_UNIT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TRANSLATION_UNIT extends SimpleNode {
  public CPPAST_TRANSLATION_UNIT(int id) {
    super(id);
  }

  public CPPAST_TRANSLATION_UNIT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7504123fe6d751a503d203a33fbfd076 (do not edit this line) */
