/* Generated By:JJTree: Do not edit this line. CPPAST_ENUMERATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_ENUMERATOR extends SimpleNode {
  public CPPAST_ENUMERATOR(int id) {
    super(id);
  }

  public CPPAST_ENUMERATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f7425c7c316ede0ec3af5e12fce7bb58 (do not edit this line) */
