/* Generated By:JJTree: Do not edit this line. CPPAST_CLASS_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_CLASS_SPECIFIER extends SimpleNode {
  public CPPAST_CLASS_SPECIFIER(int id) {
    super(id);
  }

  public CPPAST_CLASS_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7fbef28027b0cb8922f763b1d1fd5330 (do not edit this line) */
