/* Generated By:JJTree: Do not edit this line. CPPAST_SELECTION_STATEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_SELECTION_STATEMENT extends SimpleNode {
  public CPPAST_SELECTION_STATEMENT(int id) {
    super(id);
  }

  public CPPAST_SELECTION_STATEMENT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d975d6ea545712bcdd42e0fed4c0ad7d (do not edit this line) */
