/* Generated By:JJTree: Do not edit this line. CPPAST_BUILTIN_TYPE_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_BUILTIN_TYPE_SPECIFIER extends SimpleNode {
  public CPPAST_BUILTIN_TYPE_SPECIFIER(int id) {
    super(id);
  }

  public CPPAST_BUILTIN_TYPE_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bdfc6bba63c3b559d3d0e68c4d452fe6 (do not edit this line) */
