/* Generated By:JJTree: Do not edit this line. CPPAST_DTOR_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_DTOR_DECLARATOR extends SimpleNode {
  public CPPAST_DTOR_DECLARATOR(int id) {
    super(id);
  }

  public CPPAST_DTOR_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b00634148bcf9a961cd3cceaf02d34d4 (do not edit this line) */
