/* Generated By:JJTree: Do not edit this line. CPPAST_MEMBER_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_MEMBER_DECLARATION extends SimpleNode {
  public CPPAST_MEMBER_DECLARATION(int id) {
    super(id);
  }

  public CPPAST_MEMBER_DECLARATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d55ebc2b5510d52db178f6d378dd12b6 (do not edit this line) */
