/* Generated By:JJTree: Do not edit this line. CPPAST_RELATIONAL_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_RELATIONAL_EXPRESSION extends SimpleNode {
  public CPPAST_RELATIONAL_EXPRESSION(int id) {
    super(id);
  }

  public CPPAST_RELATIONAL_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d82e56f9bdbc0a54146fbbbc0e02a42 (do not edit this line) */
