/* Generated By:JJTree: Do not edit this line. CPPAST_TYPE_MODIFIERS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TYPE_MODIFIERS extends SimpleNode {
  public CPPAST_TYPE_MODIFIERS(int id) {
    super(id);
  }

  public CPPAST_TYPE_MODIFIERS(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccfd53d557c4b23c2074ea3157fc6824 (do not edit this line) */
