/* Generated By:JJTree: Do not edit this line. CPPAST_LOGICAL_OR_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_LOGICAL_OR_EXPRESSION extends SimpleNode {
  public CPPAST_LOGICAL_OR_EXPRESSION(int id) {
    super(id);
  }

  public CPPAST_LOGICAL_OR_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b6619e9e42415e3a2c7a243b01834814 (do not edit this line) */
