/* Generated By:JJTree: Do not edit this line. CPPAST_INCLUDE_SPECIFER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_INCLUDE_SPECIFER extends SimpleNode {
  public CPPAST_INCLUDE_SPECIFER(int id) {
    super(id);
  }

  public CPPAST_INCLUDE_SPECIFER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2f8754abf95a65098fbf6c574c9e1f7f (do not edit this line) */
