/* Generated By:JJTree: Do not edit this line. CPPAST_SUPERCLASS_INIT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_SUPERCLASS_INIT extends SimpleNode {
  public CPPAST_SUPERCLASS_INIT(int id) {
    super(id);
  }

  public CPPAST_SUPERCLASS_INIT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=94030434d0387052478069832573a4b0 (do not edit this line) */
