/* Generated By:JJTree: Do not edit this line. CPPAST_CTOR_INITIALIZER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_CTOR_INITIALIZER extends SimpleNode {
  public CPPAST_CTOR_INITIALIZER(int id) {
    super(id);
  }

  public CPPAST_CTOR_INITIALIZER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cbc7d9ffb59a1c0b2d78d83abfa8594d (do not edit this line) */
