/* Generated By:JJTree: Do not edit this line. CPPAST_TEMPLATE_ARGUMENT_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TEMPLATE_ARGUMENT_LIST extends SimpleNode {
  public CPPAST_TEMPLATE_ARGUMENT_LIST(int id) {
    super(id);
  }

  public CPPAST_TEMPLATE_ARGUMENT_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e010657dd46a755aa5cb8df1d7b6c672 (do not edit this line) */
