/* Generated By:JJTree: Do not edit this line. CPPAST_TEMPLATE_ARGUMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TEMPLATE_ARGUMENT extends SimpleNode {
  public CPPAST_TEMPLATE_ARGUMENT(int id) {
    super(id);
  }

  public CPPAST_TEMPLATE_ARGUMENT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb84a93041b8828ee9f4e197c209d39b (do not edit this line) */
