/* Generated By:JJTree: Do not edit this line. CPPAST_SCOPE_OVERRIDE_LOOKAHEAD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_SCOPE_OVERRIDE_LOOKAHEAD extends SimpleNode {
  public CPPAST_SCOPE_OVERRIDE_LOOKAHEAD(int id) {
    super(id);
  }

  public CPPAST_SCOPE_OVERRIDE_LOOKAHEAD(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71587cbfa6c2ecbcde5d1c3630151a6b (do not edit this line) */
