/* Generated By:JJTree: Do not edit this line. CPPAST_LINKAGE_SPECIFICATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_LINKAGE_SPECIFICATION extends SimpleNode {
  public CPPAST_LINKAGE_SPECIFICATION(int id) {
    super(id);
  }

  public CPPAST_LINKAGE_SPECIFICATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2884306b09dd76c1dcc091032395b231 (do not edit this line) */
