/* Generated By:JJTree: Do not edit this line. CPPAST_TYPE_NAME.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TYPE_NAME extends SimpleNode {
  public CPPAST_TYPE_NAME(int id) {
    super(id);
  }

  public CPPAST_TYPE_NAME(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c99e69ebaf036ed456d3eefd5b14722c (do not edit this line) */
