/* Generated By:JJTree: Do not edit this line. CPPAST_UNARY_OPERATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_UNARY_OPERATOR extends SimpleNode {
  public CPPAST_UNARY_OPERATOR(int id) {
    super(id);
  }

  public CPPAST_UNARY_OPERATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=90c930c4810279a89838a49a86553f24 (do not edit this line) */
