/* Generated By:JJTree: Do not edit this line. CPPAST_TYPE_QUALIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TYPE_QUALIFIER extends SimpleNode {
  public CPPAST_TYPE_QUALIFIER(int id) {
    super(id);
  }

  public CPPAST_TYPE_QUALIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=514d02e6cc558accf7f3a74cc6a5c6e5 (do not edit this line) */
