/* Generated By:JJTree: Do not edit this line. CPPAST_INIT_DECLARATOR_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_INIT_DECLARATOR_LIST extends SimpleNode {
  public CPPAST_INIT_DECLARATOR_LIST(int id) {
    super(id);
  }

  public CPPAST_INIT_DECLARATOR_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c21d2b80725bdbccffeb2a954740604 (do not edit this line) */
