/* Generated By:JJTree: Do not edit this line. CPPAST_PTR_OPERATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_PTR_OPERATOR extends SimpleNode {
  public CPPAST_PTR_OPERATOR(int id) {
    super(id);
  }

  public CPPAST_PTR_OPERATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=818631ba89c3fc8f60b8dc089196c30e (do not edit this line) */
