/* Generated By:JJTree: Do not edit this line. CPPAST_FUNC_DECL_DEF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_FUNC_DECL_DEF extends SimpleNode {
  public CPPAST_FUNC_DECL_DEF(int id) {
    super(id);
  }

  public CPPAST_FUNC_DECL_DEF(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=708a0aa5acc39938bcce4ca2901569e3 (do not edit this line) */
