/* Generated By:JJTree: Do not edit this line. CPPAST_LABELED_STATEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_LABELED_STATEMENT extends SimpleNode {
  public CPPAST_LABELED_STATEMENT(int id) {
    super(id);
  }

  public CPPAST_LABELED_STATEMENT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c55062228e13751c8eeb3d7977d6139e (do not edit this line) */
