/* Generated By:JJTree: Do not edit this line. CPPAST_PARAMETER_DECLARATION_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_PARAMETER_DECLARATION_LIST extends SimpleNode {
  public CPPAST_PARAMETER_DECLARATION_LIST(int id) {
    super(id);
  }

  public CPPAST_PARAMETER_DECLARATION_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=784201205eaf97f2a912bc6028c556c8 (do not edit this line) */
