/* Generated By:JJTree: Do not edit this line. CPPAST_CONVERSION_FUNCTION_DECL_OR_DEF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_CONVERSION_FUNCTION_DECL_OR_DEF extends SimpleNode {
  public CPPAST_CONVERSION_FUNCTION_DECL_OR_DEF(int id) {
    super(id);
  }

  public CPPAST_CONVERSION_FUNCTION_DECL_OR_DEF(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e98f32e617805c4541e18ab3e7f1a91b (do not edit this line) */
