/* Generated By:JJTree: Do not edit this line. CPPAST_TEMPLATE_PARAMETER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_TEMPLATE_PARAMETER extends SimpleNode {
  public CPPAST_TEMPLATE_PARAMETER(int id) {
    super(id);
  }

  public CPPAST_TEMPLATE_PARAMETER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a04e4c1822077b38c673022350cee54 (do not edit this line) */
