/* Generated By:JJTree: Do not edit this line. CPPAST_ABSTRACT_DECLARATOR_SUFFIX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_ABSTRACT_DECLARATOR_SUFFIX extends SimpleNode {
  public CPPAST_ABSTRACT_DECLARATOR_SUFFIX(int id) {
    super(id);
  }

  public CPPAST_ABSTRACT_DECLARATOR_SUFFIX(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aba8886d1050156c1cb719faa5b57141 (do not edit this line) */
