/* Generated By:JJTree: Do not edit this line. CPPAST_SIMPLE_TYPE_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_SIMPLE_TYPE_SPECIFIER extends SimpleNode {
  public CPPAST_SIMPLE_TYPE_SPECIFIER(int id) {
    super(id);
  }

  public CPPAST_SIMPLE_TYPE_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7fe00d20b21a1fde663b6fa9ee3195ab (do not edit this line) */
