/* Generated By:JJTree: Do not edit this line. CPPAST_DTOR_CTOR_DECL_SPEC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=CPPAST_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp.nodes;

import gool.parser.cpp.*;

public
class CPPAST_DTOR_CTOR_DECL_SPEC extends SimpleNode {
  public CPPAST_DTOR_CTOR_DECL_SPEC(int id) {
    super(id);
  }

  public CPPAST_DTOR_CTOR_DECL_SPEC(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8ee86f34ef934c616fa0b7991091e11a (do not edit this line) */
