#!/bin/bash

./_clean

java -cp ../../../../lib/javacc.jar jjtree CPP.jjt
java -cp ../../../../lib/javacc.jar javacc CPP.jj

#sed -i -e "s/protected Object value;/protected Object value;\n  protected Object type;\n  protected Object next;/g" SimpleNode.java
#nl=$( wc -l SimpleNode.java | cut -d" " -f1 )
#nl=$(( $nl - 3 ))
#head -n $nl SimpleNode.java > tmp
#echo -e "\n  public int jjtGetId (){ return id; }\n  public Object jjtGetType() { return type; }\n  public Object jjtGetNext() { return next; }\n" >> tmp
#tail -n 3 SimpleNode.java >> tmp
#rm SimpleNode.java
#mv tmp SimpleNode.java

sed -i -e "s/protected Object value;/protected Object value;\n  protected Object type;\n  public int jjtGetId (){ return id; }\n  public Object jjtGetType() { return type; }\n/g" SimpleNode.java

sed -i -e "s/public int jjtGetNumChildren();/public int jjtGetNumChildren(); public Object jjtGetValue(); public int jjtGetId();/g" Node.java

javac -cp .:../../../../lib/javacc.jar *.java

#java -cp . CPPParser test.cpp

