/* Generated By:JJTree: Do not edit this line. ABSTRACT_DECLARATOR_SUFFIX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ABSTRACT_DECLARATOR_SUFFIX extends SimpleNode {
  public ABSTRACT_DECLARATOR_SUFFIX(int id) {
    super(id);
  }

  public ABSTRACT_DECLARATOR_SUFFIX(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=865241309314adac852ffbc9e09b354c (do not edit this line) */
