/* Generated By:JJTree: Do not edit this line. ABSTRACT_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ABSTRACT_DECLARATOR extends SimpleNode {
  public ABSTRACT_DECLARATOR(int id) {
    super(id);
  }

  public ABSTRACT_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5db71a68dd6ed9db4b5eeb2e8d6e3313 (do not edit this line) */
