/* Generated By:JJTree: Do not edit this line. ACCESS_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ACCESS_SPECIFIER extends SimpleNode {
  public ACCESS_SPECIFIER(int id) {
    super(id);
  }

  public ACCESS_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14e19a0348e30ee422ededcf4dc3789d (do not edit this line) */
