/* Generated By:JJTree: Do not edit this line. ADDITIVE_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ADDITIVE_EXPRESSION extends SimpleNode {
  public ADDITIVE_EXPRESSION(int id) {
    super(id);
  }

  public ADDITIVE_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=645edde55815014ed5ad1f7a4f3c1d96 (do not edit this line) */
