/* Generated By:JJTree: Do not edit this line. ASSIGNMENT_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ASSIGNMENT_EXPRESSION extends SimpleNode {
  public ASSIGNMENT_EXPRESSION(int id) {
    super(id);
  }

  public ASSIGNMENT_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b84afaae803c66614dfbec4eda5f2eca (do not edit this line) */
