/* Generated By:JJTree: Do not edit this line. BUILTIN_TYPE_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class BUILTIN_TYPE_SPECIFIER extends SimpleNode {
  public BUILTIN_TYPE_SPECIFIER(int id) {
    super(id);
  }

  public BUILTIN_TYPE_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72bee3f5b558b7f05887cbf1632d8c9e (do not edit this line) */
