/* Generated By:JJTree: Do not edit this line. COMPOUND_STATEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class COMPOUND_STATEMENT extends SimpleNode {
  public COMPOUND_STATEMENT(int id) {
    super(id);
  }

  public COMPOUND_STATEMENT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6216f9f6740c66878efb6dd4233b4401 (do not edit this line) */
