/* Generated By:JJTree: Do not edit this line. CONDITIONAL_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class CONDITIONAL_EXPRESSION extends SimpleNode {
  public CONDITIONAL_EXPRESSION(int id) {
    super(id);
  }

  public CONDITIONAL_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=af8b48550fe2c56a7edeab70cf5b7880 (do not edit this line) */
