/* Generated By:JJTree: Do not edit this line. CONVERSION_FUNCTION_DECL_OR_DEF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class CONVERSION_FUNCTION_DECL_OR_DEF extends SimpleNode {
  public CONVERSION_FUNCTION_DECL_OR_DEF(int id) {
    super(id);
  }

  public CONVERSION_FUNCTION_DECL_OR_DEF(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5d30147801af4742a25f40ff7f6fdc99 (do not edit this line) */
