/* Generated By:JJTree&JavaCC: Do not edit this line. CPPParserConstants.java */
package gool.parser.cpp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CPPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LCURLYBRACE = 27;
  /** RegularExpression Id. */
  int RCURLYBRACE = 28;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 29;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 30;
  /** RegularExpression Id. */
  int LPARENTHESIS = 31;
  /** RegularExpression Id. */
  int RPARENTHESIS = 32;
  /** RegularExpression Id. */
  int SCOPE = 33;
  /** RegularExpression Id. */
  int COLON = 34;
  /** RegularExpression Id. */
  int SEMICOLON = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int QUESTIONMARK = 37;
  /** RegularExpression Id. */
  int ELLIPSIS = 38;
  /** RegularExpression Id. */
  int ASSIGNEQUAL = 39;
  /** RegularExpression Id. */
  int TIMESEQUAL = 40;
  /** RegularExpression Id. */
  int DIVIDEEQUAL = 41;
  /** RegularExpression Id. */
  int MODEQUAL = 42;
  /** RegularExpression Id. */
  int PLUSEQUAL = 43;
  /** RegularExpression Id. */
  int MINUSEQUAL = 44;
  /** RegularExpression Id. */
  int SHIFTLEFTEQUAL = 45;
  /** RegularExpression Id. */
  int SHIFTRIGHTEQUAL = 46;
  /** RegularExpression Id. */
  int BITWISEANDEQUAL = 47;
  /** RegularExpression Id. */
  int BITWISEXOREQUAL = 48;
  /** RegularExpression Id. */
  int BITWISEOREQUAL = 49;
  /** RegularExpression Id. */
  int OR = 50;
  /** RegularExpression Id. */
  int AND = 51;
  /** RegularExpression Id. */
  int BITWISEOR = 52;
  /** RegularExpression Id. */
  int BITWISEXOR = 53;
  /** RegularExpression Id. */
  int AMPERSAND = 54;
  /** RegularExpression Id. */
  int EQUAL = 55;
  /** RegularExpression Id. */
  int NOTEQUAL = 56;
  /** RegularExpression Id. */
  int LESSTHAN = 57;
  /** RegularExpression Id. */
  int GREATERTHAN = 58;
  /** RegularExpression Id. */
  int LESSTHANOREQUALTO = 59;
  /** RegularExpression Id. */
  int GREATERTHANOREQUALTO = 60;
  /** RegularExpression Id. */
  int SHIFTLEFT = 61;
  /** RegularExpression Id. */
  int SHIFTRIGHT = 62;
  /** RegularExpression Id. */
  int PLUS = 63;
  /** RegularExpression Id. */
  int MINUS = 64;
  /** RegularExpression Id. */
  int STAR = 65;
  /** RegularExpression Id. */
  int DIVIDE = 66;
  /** RegularExpression Id. */
  int MOD = 67;
  /** RegularExpression Id. */
  int PLUSPLUS = 68;
  /** RegularExpression Id. */
  int MINUSMINUS = 69;
  /** RegularExpression Id. */
  int TILDE = 70;
  /** RegularExpression Id. */
  int NOT = 71;
  /** RegularExpression Id. */
  int DOT = 72;
  /** RegularExpression Id. */
  int POINTERTO = 73;
  /** RegularExpression Id. */
  int DOTSTAR = 74;
  /** RegularExpression Id. */
  int ARROWSTAR = 75;
  /** RegularExpression Id. */
  int AUTO = 76;
  /** RegularExpression Id. */
  int BREAK = 77;
  /** RegularExpression Id. */
  int CASE = 78;
  /** RegularExpression Id. */
  int CATCH = 79;
  /** RegularExpression Id. */
  int CHAR = 80;
  /** RegularExpression Id. */
  int CONST = 81;
  /** RegularExpression Id. */
  int CONTINUE = 82;
  /** RegularExpression Id. */
  int _DEFAULT = 83;
  /** RegularExpression Id. */
  int DELETE = 84;
  /** RegularExpression Id. */
  int DO = 85;
  /** RegularExpression Id. */
  int DOUBLE = 86;
  /** RegularExpression Id. */
  int ELSE = 87;
  /** RegularExpression Id. */
  int ENUM = 88;
  /** RegularExpression Id. */
  int EXTERN = 89;
  /** RegularExpression Id. */
  int FLOAT = 90;
  /** RegularExpression Id. */
  int FOR = 91;
  /** RegularExpression Id. */
  int FRIEND = 92;
  /** RegularExpression Id. */
  int GOTO = 93;
  /** RegularExpression Id. */
  int IF = 94;
  /** RegularExpression Id. */
  int INLINE = 95;
  /** RegularExpression Id. */
  int INT = 96;
  /** RegularExpression Id. */
  int LONG = 97;
  /** RegularExpression Id. */
  int NEW = 98;
  /** RegularExpression Id. */
  int PRIVATE = 99;
  /** RegularExpression Id. */
  int PROTECTED = 100;
  /** RegularExpression Id. */
  int PUBLIC = 101;
  /** RegularExpression Id. */
  int REDECLARED = 102;
  /** RegularExpression Id. */
  int REGISTER = 103;
  /** RegularExpression Id. */
  int RETURN = 104;
  /** RegularExpression Id. */
  int SHORT = 105;
  /** RegularExpression Id. */
  int SIGNED = 106;
  /** RegularExpression Id. */
  int SIZEOF = 107;
  /** RegularExpression Id. */
  int STATIC = 108;
  /** RegularExpression Id. */
  int STRUCT = 109;
  /** RegularExpression Id. */
  int CLASS = 110;
  /** RegularExpression Id. */
  int SWITCH = 111;
  /** RegularExpression Id. */
  int TEMPLATE = 112;
  /** RegularExpression Id. */
  int THIS = 113;
  /** RegularExpression Id. */
  int TRY = 114;
  /** RegularExpression Id. */
  int TYPEDEF = 115;
  /** RegularExpression Id. */
  int UNION = 116;
  /** RegularExpression Id. */
  int UNSIGNED = 117;
  /** RegularExpression Id. */
  int VIRTUAL = 118;
  /** RegularExpression Id. */
  int VOID = 119;
  /** RegularExpression Id. */
  int VOLATILE = 120;
  /** RegularExpression Id. */
  int WHILE = 121;
  /** RegularExpression Id. */
  int OPERATOR = 122;
  /** RegularExpression Id. */
  int TRUETOK = 123;
  /** RegularExpression Id. */
  int FALSETOK = 124;
  /** RegularExpression Id. */
  int THROW = 125;
  /** RegularExpression Id. */
  int INCLUDE = 126;
  /** RegularExpression Id. */
  int OCTALINT = 127;
  /** RegularExpression Id. */
  int OCTALLONG = 128;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALINT = 129;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALLONG = 130;
  /** RegularExpression Id. */
  int DECIMALINT = 131;
  /** RegularExpression Id. */
  int DECIMALLONG = 132;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALINT = 133;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALLONG = 134;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 135;
  /** RegularExpression Id. */
  int HEXADECIMALLONG = 136;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALINT = 137;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALLONG = 138;
  /** RegularExpression Id. */
  int FLOATONE = 139;
  /** RegularExpression Id. */
  int FLOATTWO = 140;
  /** RegularExpression Id. */
  int CHARACTER = 141;
  /** RegularExpression Id. */
  int PATH_STRING = 142;
  /** RegularExpression Id. */
  int STRING = 143;
  /** RegularExpression Id. */
  int ID = 146;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"//\"",
    "\"/*\"",
    "\"#define\"",
    "\"#undef\"",
    "\"#ifdef\"",
    "\"#ifndef\"",
    "\"#if\"",
    "\"#elif\"",
    "\"#else\"",
    "\"#endif\"",
    "\"#error\"",
    "\"#line\"",
    "\"#pragma\"",
    "\"# \"",
    "\"\\n\"",
    "<token of kind 20>",
    "\"*/\"",
    "<token of kind 22>",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 26>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"class\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"try\"",
    "\"typedef\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"operator\"",
    "\"true\"",
    "\"false\"",
    "\"throw\"",
    "\"#include\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<PATH_STRING>",
    "<STRING>",
    "\"bool\"",
    "\"finally\"",
    "<ID>",
  };

}
