/* Generated By:JJTree: Do not edit this line. CTOR_DECLARATOR_LOOKAHEAD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class CTOR_DECLARATOR_LOOKAHEAD extends SimpleNode {
  public CTOR_DECLARATOR_LOOKAHEAD(int id) {
    super(id);
  }

  public CTOR_DECLARATOR_LOOKAHEAD(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2da3c0e38a983b5b6283e7fa2a8688fb (do not edit this line) */
