/* Generated By:JJTree: Do not edit this line. CTOR_DEFINITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class CTOR_DEFINITION extends SimpleNode {
  public CTOR_DEFINITION(int id) {
    super(id);
  }

  public CTOR_DEFINITION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e9b636e3831df8c08a49e7f9f514f8ee (do not edit this line) */
