/* Generated By:JJTree: Do not edit this line. CV_QUALIFIER_SEQ.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class CV_QUALIFIER_SEQ extends SimpleNode {
  public CV_QUALIFIER_SEQ(int id) {
    super(id);
  }

  public CV_QUALIFIER_SEQ(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6a261a766ab97dfba6cbb837c2fca31f (do not edit this line) */
