/* Generated By:JJTree: Do not edit this line. DECLARATOR_SUFFIXES.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DECLARATOR_SUFFIXES extends SimpleNode {
  public DECLARATOR_SUFFIXES(int id) {
    super(id);
  }

  public DECLARATOR_SUFFIXES(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=df248c45f377ffdfb440d7045f46fab9 (do not edit this line) */
