/* Generated By:JJTree: Do not edit this line. DECLARATION_SPECIFIERS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DECLARATION_SPECIFIERS extends SimpleNode {
  public DECLARATION_SPECIFIERS(int id) {
    super(id);
  }

  public DECLARATION_SPECIFIERS(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=460c9206384ca81069a18fa42527a29f (do not edit this line) */
