/* Generated By:JJTree: Do not edit this line. DELETE_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DELETE_EXPRESSION extends SimpleNode {
  public DELETE_EXPRESSION(int id) {
    super(id);
  }

  public DELETE_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=550aeba4bf31c9ad46a2281e2ada7529 (do not edit this line) */
