/* Generated By:JJTree: Do not edit this line. DIRECT_NEW_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DIRECT_NEW_DECLARATOR extends SimpleNode {
  public DIRECT_NEW_DECLARATOR(int id) {
    super(id);
  }

  public DIRECT_NEW_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b85b51c57ab783eaf3d8a2fd7fc545ba (do not edit this line) */
