/* Generated By:JJTree: Do not edit this line. DIRECT_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DIRECT_DECLARATOR extends SimpleNode {
  public DIRECT_DECLARATOR(int id) {
    super(id);
  }

  public DIRECT_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=58c02c21023af10ce54fbd69664aeb90 (do not edit this line) */
