/* Generated By:JJTree: Do not edit this line. DTOR_CTOR_DECL_SPEC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DTOR_CTOR_DECL_SPEC extends SimpleNode {
  public DTOR_CTOR_DECL_SPEC(int id) {
    super(id);
  }

  public DTOR_CTOR_DECL_SPEC(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e3052e98403d392eab1c69e0a84f910 (do not edit this line) */
