/* Generated By:JJTree: Do not edit this line. DTOR_DEFINITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class DTOR_DEFINITION extends SimpleNode {
  public DTOR_DEFINITION(int id) {
    super(id);
  }

  public DTOR_DEFINITION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7395e55b2c75fee3249b10119663edc6 (do not edit this line) */
