/* Generated By:JJTree: Do not edit this line. ENUMERATOR_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ENUMERATOR_LIST extends SimpleNode {
  public ENUMERATOR_LIST(int id) {
    super(id);
  }

  public ENUMERATOR_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f0fac319415f3e4d2a43f6a5961b7954 (do not edit this line) */
