/* Generated By:JJTree: Do not edit this line. EQUALITY_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class EQUALITY_EXPRESSION extends SimpleNode {
  public EQUALITY_EXPRESSION(int id) {
    super(id);
  }

  public EQUALITY_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=750209db19101cdc937f0010de869d71 (do not edit this line) */
