/* Generated By:JJTree: Do not edit this line. EXCEPTION_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class EXCEPTION_DECLARATION extends SimpleNode {
  public EXCEPTION_DECLARATION(int id) {
    super(id);
  }

  public EXCEPTION_DECLARATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95d5680275f6bf9afe05684329877729 (do not edit this line) */
