/* Generated By:JJTree: Do not edit this line. EXCEPTION_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class EXCEPTION_LIST extends SimpleNode {
  public EXCEPTION_LIST(int id) {
    super(id);
  }

  public EXCEPTION_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e4a8f769231e03be9e0f6b4b3e276465 (do not edit this line) */
