/* Generated By:JJTree: Do not edit this line. EXPRESSION_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class EXPRESSION_LIST extends SimpleNode {
  public EXPRESSION_LIST(int id) {
    super(id);
  }

  public EXPRESSION_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80f1f94ee5d1a07a7a02b58a67386996 (do not edit this line) */
