/* Generated By:JJTree: Do not edit this line. EXTERNAL_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class EXTERNAL_DECLARATION extends SimpleNode {
  public EXTERNAL_DECLARATION(int id) {
    super(id);
  }

  public EXTERNAL_DECLARATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ef8e10653b9ec652e1a1f9029de30c58 (do not edit this line) */
