/* Generated By:JJTree: Do not edit this line. FUNCTION_DEFINITION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class FUNCTION_DEFINITION extends SimpleNode {
  public FUNCTION_DEFINITION(int id) {
    super(id);
  }

  public FUNCTION_DEFINITION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=58b45b3bd8d332ed1cc0afa9b97ea8f0 (do not edit this line) */
