/* Generated By:JJTree: Do not edit this line. FUNC_DECL_DEF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class FUNC_DECL_DEF extends SimpleNode {
  public FUNC_DECL_DEF(int id) {
    super(id);
  }

  public FUNC_DECL_DEF(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e290c1ba3031a0709ebdc2ad40034761 (do not edit this line) */
