/* Generated By:JJTree: Do not edit this line. FUNCTION_DIRECT_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class FUNCTION_DIRECT_DECLARATOR extends SimpleNode {
  public FUNCTION_DIRECT_DECLARATOR(int id) {
    super(id);
  }

  public FUNCTION_DIRECT_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=93fa3b299110527e162b9d83fc1f48d8 (do not edit this line) */
