/* Generated By:JJTree: Do not edit this line. INCLUDE_SPECIFER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class INCLUDE_SPECIFER extends SimpleNode {
  public INCLUDE_SPECIFER(int id) {
    super(id);
  }

  public INCLUDE_SPECIFER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=76fb8a023302fd4842644deae52e6ede (do not edit this line) */
