/* Generated By:JJTree: Do not edit this line. ITERATION_STATEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class ITERATION_STATEMENT extends SimpleNode {
  public ITERATION_STATEMENT(int id) {
    super(id);
  }

  public ITERATION_STATEMENT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=67f9e97b5cc2054fbf385839585e11ed (do not edit this line) */
