/* Generated By:JJTree: Do not edit this line. LINKAGE_SPECIFICATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class LINKAGE_SPECIFICATION extends SimpleNode {
  public LINKAGE_SPECIFICATION(int id) {
    super(id);
  }

  public LINKAGE_SPECIFICATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db5600b0c1e6d863318f9b882f0c53eb (do not edit this line) */
