/* Generated By:JJTree: Do not edit this line. LOGICAL_AND_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class LOGICAL_AND_EXPRESSION extends SimpleNode {
  public LOGICAL_AND_EXPRESSION(int id) {
    super(id);
  }

  public LOGICAL_AND_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aaf02fefab9eec94449d5f86904051f6 (do not edit this line) */
