/* Generated By:JJTree: Do not edit this line. MULTIPLICATIVE_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class MULTIPLICATIVE_EXPRESSION extends SimpleNode {
  public MULTIPLICATIVE_EXPRESSION(int id) {
    super(id);
  }

  public MULTIPLICATIVE_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1e8fb39ae962fb993b2c7ffa9d31ff25 (do not edit this line) */
