/* Generated By:JJTree: Do not edit this line. NEW_TYPE_ID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class NEW_TYPE_ID extends SimpleNode {
  public NEW_TYPE_ID(int id) {
    super(id);
  }

  public NEW_TYPE_ID(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3033c73f89f1054a60c8b96fe6288ed4 (do not edit this line) */
