/* Generated By:JJTree: Do not edit this line. PARAMETER_DECLARATION_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class PARAMETER_DECLARATION_LIST extends SimpleNode {
  public PARAMETER_DECLARATION_LIST(int id) {
    super(id);
  }

  public PARAMETER_DECLARATION_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=01bef831e2a92360103a5a1d24140e3c (do not edit this line) */
