/* Generated By:JJTree: Do not edit this line. PARAMETER_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class PARAMETER_LIST extends SimpleNode {
  public PARAMETER_LIST(int id) {
    super(id);
  }

  public PARAMETER_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=10e28b6e3b8263ddf0cdcc8ee24fe9f3 (do not edit this line) */
