/* Generated By:JJTree: Do not edit this line. PARAMETER_DECLARATION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class PARAMETER_DECLARATION extends SimpleNode {
  public PARAMETER_DECLARATION(int id) {
    super(id);
  }

  public PARAMETER_DECLARATION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b61d95b5d82fbe117d572aecffea765c (do not edit this line) */
