/* Generated By:JJTree: Do not edit this line. POSTFIX_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class POSTFIX_EXPRESSION extends SimpleNode {
  public POSTFIX_EXPRESSION(int id) {
    super(id);
  }

  public POSTFIX_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9b4466d647ba12f939888fec648491db (do not edit this line) */
