/* Generated By:JJTree: Do not edit this line. PRIMARY_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class PRIMARY_EXPRESSION extends SimpleNode {
  public PRIMARY_EXPRESSION(int id) {
    super(id);
  }

  public PRIMARY_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2f826dd6ddd71621818bd5b80531b9ea (do not edit this line) */
