/* Generated By:JJTree: Do not edit this line. PTR_TO_MEMBER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class PTR_TO_MEMBER extends SimpleNode {
  public PTR_TO_MEMBER(int id) {
    super(id);
  }

  public PTR_TO_MEMBER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7d3d33e293320c376da2c63997a0d611 (do not edit this line) */
