/* Generated By:JJTree: Do not edit this line. PTR_OPERATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class PTR_OPERATOR extends SimpleNode {
  public PTR_OPERATOR(int id) {
    super(id);
  }

  public PTR_OPERATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=20ca5d786b78dc9b066487ab9e1824b7 (do not edit this line) */
