/* Generated By:JJTree: Do not edit this line. QUALIFIED_ID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class QUALIFIED_ID extends SimpleNode {
  public QUALIFIED_ID(int id) {
    super(id);
  }

  public QUALIFIED_ID(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3deb0d48a9ef0da0050864a620f51c70 (do not edit this line) */
