/* Generated By:JJTree: Do not edit this line. RELATIONAL_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class RELATIONAL_EXPRESSION extends SimpleNode {
  public RELATIONAL_EXPRESSION(int id) {
    super(id);
  }

  public RELATIONAL_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=be0165eaae30a3fcad89699f79c3a004 (do not edit this line) */
