/* Generated By:JJTree: Do not edit this line. SCOPE_OVERRIDE_LOOKAHEAD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class SCOPE_OVERRIDE_LOOKAHEAD extends SimpleNode {
  public SCOPE_OVERRIDE_LOOKAHEAD(int id) {
    super(id);
  }

  public SCOPE_OVERRIDE_LOOKAHEAD(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c28551ed6578602671c5c427214c2c3 (do not edit this line) */
