/* Generated By:JJTree: Do not edit this line. SCOPE_OVERRIDE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class SCOPE_OVERRIDE extends SimpleNode {
  public SCOPE_OVERRIDE(int id) {
    super(id);
  }

  public SCOPE_OVERRIDE(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=afa5f1ce61a72720ce392dc5afb60863 (do not edit this line) */
