/* Generated By:JJTree: Do not edit this line. SHIFT_EXPRESSION.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class SHIFT_EXPRESSION extends SimpleNode {
  public SHIFT_EXPRESSION(int id) {
    super(id);
  }

  public SHIFT_EXPRESSION(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aa3963d8ccdec83cc4e9cb6d47e15af5 (do not edit this line) */
