/* Generated By:JJTree: Do not edit this line. SIMPLE_DTOR_DECLARATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class SIMPLE_DTOR_DECLARATOR extends SimpleNode {
  public SIMPLE_DTOR_DECLARATOR(int id) {
    super(id);
  }

  public SIMPLE_DTOR_DECLARATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71eb938eba5685a9fd0f3775d857064f (do not edit this line) */
