/* Generated By:JJTree: Do not edit this line. SIMPLE_TYPE_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class SIMPLE_TYPE_SPECIFIER extends SimpleNode {
  public SIMPLE_TYPE_SPECIFIER(int id) {
    super(id);
  }

  public SIMPLE_TYPE_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7505d1e6854c1ea43e867e4c935ff026 (do not edit this line) */
