/* Generated By:JJTree: Do not edit this line. STATEMENT_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class STATEMENT_LIST extends SimpleNode {
  public STATEMENT_LIST(int id) {
    super(id);
  }

  public STATEMENT_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6a2a7fed317a90c5297abbf20bdd933c (do not edit this line) */
