/* Generated By:JJTree: Do not edit this line. STORAGE_CLASS_SPECIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class STORAGE_CLASS_SPECIFIER extends SimpleNode {
  public STORAGE_CLASS_SPECIFIER(int id) {
    super(id);
  }

  public STORAGE_CLASS_SPECIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1728efd6d6db7704c5ba92887403ef84 (do not edit this line) */
