/* Generated By:JJTree: Do not edit this line. TEMPLATE_HEAD.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TEMPLATE_HEAD extends SimpleNode {
  public TEMPLATE_HEAD(int id) {
    super(id);
  }

  public TEMPLATE_HEAD(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=14439d30339014c8dbab12f25694140c (do not edit this line) */
