/* Generated By:JJTree: Do not edit this line. TEMPLATE_ARGUMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TEMPLATE_ARGUMENT extends SimpleNode {
  public TEMPLATE_ARGUMENT(int id) {
    super(id);
  }

  public TEMPLATE_ARGUMENT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c13a4a9958d4a22bc07fffbf936d689f (do not edit this line) */
