/* Generated By:JJTree: Do not edit this line. TEMPLATE_PARAMETER_LIST.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TEMPLATE_PARAMETER_LIST extends SimpleNode {
  public TEMPLATE_PARAMETER_LIST(int id) {
    super(id);
  }

  public TEMPLATE_PARAMETER_LIST(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=579e760b2c36d7ccd008193b80103035 (do not edit this line) */
