/* Generated By:JJTree: Do not edit this line. TEMPLATE_PARAMETER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TEMPLATE_PARAMETER extends SimpleNode {
  public TEMPLATE_PARAMETER(int id) {
    super(id);
  }

  public TEMPLATE_PARAMETER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f5cae3c3a9d769f697c5e8e2151f123 (do not edit this line) */
