/* Generated By:JJTree: Do not edit this line. TRANSLATION_UNIT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TRANSLATION_UNIT extends SimpleNode {
  public TRANSLATION_UNIT(int id) {
    super(id);
  }

  public TRANSLATION_UNIT(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e860c40b912e99b5cd265a944a87d9f1 (do not edit this line) */
