/* Generated By:JJTree: Do not edit this line. TYPE_MODIFIERS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TYPE_MODIFIERS extends SimpleNode {
  public TYPE_MODIFIERS(int id) {
    super(id);
  }

  public TYPE_MODIFIERS(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2a9588f2a68069ae47be273fec9d23a2 (do not edit this line) */
