/* Generated By:JJTree: Do not edit this line. TYPE_QUALIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TYPE_QUALIFIER extends SimpleNode {
  public TYPE_QUALIFIER(int id) {
    super(id);
  }

  public TYPE_QUALIFIER(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cdb1f07c1047fdba010ff0dceffe9bae (do not edit this line) */
