/* Generated By:JJTree: Do not edit this line. TYPE_NAME.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class TYPE_NAME extends SimpleNode {
  public TYPE_NAME(int id) {
    super(id);
  }

  public TYPE_NAME(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07e8ff1045a861ee881ef93d53e1a884 (do not edit this line) */
