/* Generated By:JJTree: Do not edit this line. UNARY_OPERATOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package gool.parser.cpp;

public
class UNARY_OPERATOR extends SimpleNode {
  public UNARY_OPERATOR(int id) {
    super(id);
  }

  public UNARY_OPERATOR(CPPParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CPPParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9667ade7df8512ec7cf17ecd9c805ed4 (do not edit this line) */
